- name: setuptools is installed
  yum: name={{ item }} state=installed
  with_items:
    - python-setuptools
  tags: install_setuptools

- name: pip is installed
  easy_install: name={{ item }}
  with_items:
    - pip 
  tags: install_pip

- name: httplib2 are installed
  pip: name={{ item }}
  with_items:
    - httplib2
  tags: install_httplib2
